name: Backup a S3

on:
  push:
    branches: [ "**" ]   # se ejecuta en cada commit/push a cualquier rama

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Sincronizar con S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET }}/${{ github.repository }}/ --exclude ".git/*" --delete
